apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rk08l4x6o-python
  janus-idp.io/tekton: rk08l4x6o-python
  backstage.io/kubernetes-id: rk08l4x6o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rk08l4x6o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
